# Generated by Django 5.0.3 on 2024-04-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_post_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='absence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.absence'),
        ),
        migrations.AddField(
            model_name='post',
            name='carpooling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carpooling'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.category'),
        ),
        migrations.AlterField(
            model_name='carpooling',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpoolings', to='core.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.category'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='event',
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event'),
        ),
    ]
