# Generated by Django 5.0.3 on 2024-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_logement_post_logement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='typestage',
            field=models.IntegerField(max_length=255),
        ),
    ]
