# Generated by Django 5.0.3 on 2024-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_stage_typestage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='departure_time',
            field=models.DateField(),
        ),
    ]
